#ifndef NDTR_ENGINE_GLOBAL_H
#define NDTR_ENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NDTR_ENGINE_LIBRARY)
#  define NDTR_ENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define NDTR_ENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NDTR_ENGINE_GLOBAL_H
